// socket actions

const SOCKET_ACTION = "SOCKET_ACTION";
const SOCKET_USER_AUTHORIZATION = "USER_AUTHORIZATION";
const SOCKET_USER_LOGOUT = "USER_LOGOUT";
const SOCKET_TODO_CREATION = "TODO_CREATION";
const SOCKET_TODO_UPDATE = "TODO_UPDATE";
const SOCKET_TODO_CHECK = "TODO_CHECK";
const SOCKET_TODO_DELETE = "TODO_DELETE";
const SOCKET_TODO_CLEAR_COMPLETED = "SOCKET_TODO_CLEAR_COMPLETED";
const SOCKET_SHARE_TODOS = "SOCKET_SHARE_TODOS";

export {
	SOCKET_ACTION,
	SOCKET_SHARE_TODOS,
	SOCKET_TODO_CHECK,
	SOCKET_TODO_CLEAR_COMPLETED,
	SOCKET_TODO_CREATION,
	SOCKET_TODO_DELETE,
	SOCKET_TODO_UPDATE,
	SOCKET_USER_AUTHORIZATION,
	SOCKET_USER_LOGOUT,
};
