// socket actions

const SOCKET_ACTION = "SOCKET_ACTION";
const SOCKET_USER_AUTHORIZATION = "USER_AUTHORIZATION";
const SOCKET_USER_LOGOUT = "USER_LOGOUT";
const SOCKET_TODO_CREATION = "TODO_CREATION";
const SOCKET_TODO_UPDATE = "TODO_UPDATE";
const SOCKET_TODO_CHECK = "TODO_CHECK";
const SOCKET_TODO_DELETE = "TODO_DELETE";

export {
    SOCKET_ACTION,
    SOCKET_USER_AUTHORIZATION,
    SOCKET_USER_LOGOUT,
    SOCKET_TODO_CHECK,
    SOCKET_TODO_CREATION,
    SOCKET_TODO_DELETE,
    SOCKET_TODO_UPDATE,
};
