// gender
const GENDER_MALE = 0;
const GENDER_FEMALE = 1;
const GENDER_OTHER = 2;

// heard from
const HEARD_FROM_FRIEND = 0;
const HEARD_FROM_INTERNET = 1;
const HEARD_FROM_ADVERTISEMENT = 2;
const HEARD_FROM_OTHER = 3;

// requests
const POST_REQUEST = "POST";
const PUT_REQUEST = "PUT";
const GET_REQUEST = "GET";
const PATCH_REQUEST = "PATCH";
const DELETE_REQUEST = "DELETE";

// limits
const TODOS_LIMIT = 4;
const USERS_LIMIT = 3;

// filters
const FILTER_ALL = 0;
const FILTER_ACTIVE = 1;
const FILTER_COMPLETED = 2;

// socket actions

const SOCKET_ACTION = "SOCKET_ACTION";
const SOCKET_USER_AUTHORIZATION = "USER_AUTHORIZATION";
const SOCKET_USER_LOGOUT = "USER_LOGOUT";
const SOCKET_TODO_CREATION = "TODO_CREATION";
const SOCKET_TODO_UPDATE = "TODO_UPDATE";
const SOCKET_TODO_CHECK = "TODO_CHECK";
const SOCKET_TODO_DELETE = "TODO_DELETE";
const SOCKET_TODO_CLEAR_COMPLETED = "SOCKET_TODO_CLEAR_COMPLETED";
const SOCKET_CONNECTION_REFRESH = "SOCKET_CONNECTION_REFRESH";

export {
    GENDER_MALE,
    GENDER_FEMALE,
    GENDER_OTHER,
    HEARD_FROM_FRIEND,
    HEARD_FROM_INTERNET,
    HEARD_FROM_ADVERTISEMENT,
    HEARD_FROM_OTHER,
    POST_REQUEST,
    PUT_REQUEST,
    GET_REQUEST,
    PATCH_REQUEST,
    DELETE_REQUEST,
    TODOS_LIMIT,
    USERS_LIMIT,
    FILTER_ALL,
    FILTER_ACTIVE,
    FILTER_COMPLETED,
    SOCKET_ACTION,
    SOCKET_USER_AUTHORIZATION,
    SOCKET_USER_LOGOUT,
    SOCKET_TODO_CHECK,
    SOCKET_TODO_CREATION,
    SOCKET_TODO_DELETE,
    SOCKET_TODO_UPDATE,
    SOCKET_TODO_CLEAR_COMPLETED,
    SOCKET_CONNECTION_REFRESH,
};
