const GENDER_MALE = 0;
const GENDER_FEMALE = 1;
const GENDER_OTHER = 2;

const HEARD_FROM_FRIEND = 0;
const HEARD_FROM_INTERNET = 1;
const HEARD_FROM_ADVERTISEMENT = 2;
const HEARD_FROM_OTHER = 3;

const POST_REQUEST = "POST";
const PUT_REQUEST = "PUT";
const GET_REQUEST = "GET";
const PATCH_REQUEST = "PATCH";
const DELETE_REQUEST = "DELETE";

export {
    GENDER_MALE,
    GENDER_FEMALE,
    GENDER_OTHER,
    HEARD_FROM_FRIEND,
    HEARD_FROM_INTERNET,
    HEARD_FROM_ADVERTISEMENT,
    HEARD_FROM_OTHER,
    POST_REQUEST,
    PUT_REQUEST,
    GET_REQUEST,
    PATCH_REQUEST,
    DELETE_REQUEST,
};
