export const actionRequestType = {
    ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
    CHECK_TODO_REQUEST: "CHECK_TODO_REQUEST",
    EDIT_TODO_REQUEST: "EDIT_TODO_REQUEST",
    DELETE_TODO_REQUEST: "DELETE_TODO_REQUEST",
    SET_FILTER_REQUEST: "SET_FILTER_REQUEST",
};

export const actionSuccessType = {
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    CHECK_TODO_SUCCESS: "CHECK_TODO_SUCCESS",
    EDIT_TODO_SUCCESS: "EDIT_TODO_SUCCESS",
    DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
    SET_FILTER_SUCCESS: "SET_FILTER_SUCCESS",
};

export const stateActionType = {
    STATE_UPDATED: "STATE_UPDATED",
};
