export const actionRequestType = {
    ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
    CHECK_TODO_REQUEST: "CHECK_TODO_REQUEST",
    EDIT_TODO_REQUEST: "EDIT_TODO_REQUEST",
    DELETE_TODO_REQUEST: "DELETE_TODO_REQUEST",
    SET_FILTER_REQUEST: "SET_FILTER_REQUEST",
    CLEAR_COMPLETED_REQUEST: "CLEAR_COMPLETED_REQUEST",
    REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
    LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
};

export const actionSuccessType = {
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    CHECK_TODO_SUCCESS: "CHECK_TODO_SUCCESS",
    EDIT_TODO_SUCCESS: "EDIT_TODO_SUCCESS",
    DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
    SET_FILTER_SUCCESS: "SET_FILTER_SUCCESS",
    CLEAR_COMPLETED_SUCCESS: "CLEAR_COMPLETED_SUCCESS",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
};

export const actionFailureType = {
    ADD_TODO_FAILURE: "ADD_TODO_FAILURE",
    CHECK_TODO_FAILURE: "CHECK_TODO_FAILURE",
    EDIT_TODO_FAILURE: "EDIT_TODO_FAILURE",
    DELETE_TODO_FAILURE: "DELETE_TODO_FAILURE",
    SET_FILTER_FAILURE: "SET_FILTER_FAILURE",
    CLEAR_COMPLETED_FAILURE: "CLEAR_COMPLETED_FAILURE",
    REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
    LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
};

export const stateActionType = {
    STATE_UPDATED: "STATE_UPDATED",
};
